<a href="https://colab.research.google.com/github/Alee-M/Taking_a_Swing_at_Probability_Neural_Networks_Comparison/blob/main/BNN_Ensemble_Comparison_Data_Cleaning_Final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Setup

In [1]:
#Connect to Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
#Import necessary packages
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

In [3]:
#Set Directory
dir = ' '

###2017 Data

Start: 4/2/2017
ASG: 7/11/2017
EOS: 10/1/2017

In [4]:
#ASG data represents SO/PA at the midpoint of the baseball season (the All-Star Break)
ASG2017 = pd.read_csv(dir + '2017_Start_ASG_160_AB.csv') #Load in CSV (direct export from FanGraphs)
ASG2017 = ASG2017[['playerId','SO','PA']] #Remove unnecessary columns
ASG2017

     playerId  SO   PA
0         393  37  286
1         589  66  313
2         785  67  322
3         791  42  326
4        1159  42  196
..        ...  ..  ...
269     17901  56  354
270     17919  61  203
271     18314  77  335
272     18721  28  229
273     19198  37  308

[274 rows x 3 columns]

In [5]:
#EOS data represents SO/PA with full season data
EOS2017 = pd.read_csv(dir + '2017_Start_EOS_160_AB.csv') #Load in CSV (direct export from FanGraphs)
EOS2017 = EOS2017[['playerId','SO','PA']] #Remove unnecesaary columns
EOS2017['SO/PA'] = EOS2017['SO']/EOS2017['PA'] #Calculate strikeout rate
EOS2017=EOS2017.drop(columns=['PA','SO']) #Drop columns used for calculation
EOS2017

     playerId     SO/PA
0         393  0.144828
1         589  0.200393
2         639  0.133676
3         785  0.217014
4         791  0.120861
..        ...       ...
368     18015  0.279910
369     18314  0.217786
370     18718  0.192469
371     18721  0.150235
372     19198  0.109929

[373 rows x 2 columns]

In [6]:
#Create merged data for 2017
data2017 = pd.merge(ASG2017, EOS2017, on=['playerId'], how='inner') #Merge data at All-Star_Break with data at End of Season, inner join -> only players in both datasets
data2017=data2017.dropna() #Drop rows with blank values
data2017

     playerId  SO   PA     SO/PA
0         393  37  286  0.144828
1         589  66  313  0.200393
2         785  67  322  0.217014
3         791  42  326  0.120861
4        1159  42  196  0.192529
..        ...  ..  ...       ...
269     17901  56  354  0.170213
270     17919  61  203  0.312349
271     18314  77  335  0.217786
272     18721  28  229  0.150235
273     19198  37  308  0.109929

[274 rows x 4 columns]

### 2018 Data

Start: 3/29/2018
ASG: 7/17/2018
EOS: 10/1/2018

In [7]:
#ASG data represents SO/PA at the midpoint of the baseball season (the All-Star Break)
ASG2018 = pd.read_csv(dir + '2018_Start_ASG_160_AB.csv') #Load in CSV (direct export from FanGraphs)
ASG2018 = ASG2018[['playerId','SO','PA']] #Remove unnecessary columns
ASG2018

     playerId  SO   PA
0         393  32  326
1         639  55  261
2         785  58  260
3        1177  52  368
4        1433  61  315
..        ...  ..  ...
270     18314  79  327
271     18401  56  184
272     18721  46  244
273     19198  34  335
274     20123  41  209

[275 rows x 3 columns]

In [8]:
#EOS data represents SO/PA with full season data
EOS2018 = pd.read_csv(dir + '2018_Start_EOS_160_AB.csv') #Load in CSV (direct export from FanGraphs)
EOS2018 = EOS2018[['playerId','SO','PA']] #Remove unnecesaary columns
EOS2018['SO/PA'] = EOS2018['SO']/EOS2018['PA'] #Calculate strikeout rate
EOS2018=EOS2018.drop(columns=['PA','SO']) #Drop columns used for calculation
EOS2018

     playerId     SO/PA
0         393  0.096457
1         639  0.199584
2         785  0.237288
3        1177  0.130522
4        1433  0.192308
..        ...       ...
366     18721  0.154303
367     19198  0.109948
368     19238  0.224335
369     19755  0.277929
370     20123  0.200405

[371 rows x 2 columns]

In [9]:
#Create merged data for 2018
data2018 = pd.merge(ASG2018, EOS2018, on=['playerId'], how='inner') #Merge data at All-Star_Break with data at End of Season, inner join -> only players in both datasets
data2018=data2018.dropna() #Drop rows with blank values
data2018

     playerId  SO   PA     SO/PA
0         393  32  326  0.096457
1         639  55  261  0.199584
2         785  58  260  0.237288
3        1177  52  368  0.130522
4        1433  61  315  0.192308
..        ...  ..  ...       ...
270     18314  79  327  0.228893
271     18401  56  184  0.252567
272     18721  46  244  0.154303
273     19198  34  335  0.109948
274     20123  41  209  0.200405

[275 rows x 4 columns]

### 2019 Data

Start: 3/20/2019
ASG: 7/9/2019
EOS: 9/29/2019

In [10]:
#ASG data represents SO/PA at the midpoint of the baseball season (the All-Star Break)
ASG2019 = pd.read_csv(dir + '2019_Start_ASG_160_AB.csv') #Load in CSV (direct export from FanGraphs)
ASG2019 = ASG2019[['playerId','SO','PA']] #Remove unnecessary columns
ASG2019

     playerId  SO   PA
0         785  46  247
1        1177  35  295
2        1433  44  281
3        1744  64  319
4        2136  72  324
..        ...  ..  ...
267     19611  47  253
268     19709  67  234
269     19755  53  218
270     19858  44  202
271     20123  73  342

[272 rows x 3 columns]

In [11]:
#EOS data represents SO/PA with full season data
EOS2019 = pd.read_csv(dir + '2019_Start_EOS_160_AB.csv') #Load in CSV (direct export from FanGraphs)
EOS2019 = EOS2019[['playerId','SO','PA']] #Remove unnecesaary columns
EOS2019['SO/PA'] = EOS2019['SO']/EOS2019['PA'] #Calculate strikeout rate
EOS2019=EOS2019.drop(columns=['PA','SO']) #Drop columns used for calculation
EOS2019

     playerId     SO/PA
0         785  0.212425
1        1177  0.124771
2        1433  0.131679
3        1744  0.196721
4        2136  0.205674
..        ...       ...
376     19755  0.258824
377     19858  0.229064
378     19878  0.247934
379     20003  0.307471
380     20123  0.200303

[381 rows x 2 columns]

In [12]:
#Create merged data for 2019
data2019 = pd.merge(ASG2019, EOS2019, on=['playerId'], how='inner') #Merge data at All-Star_Break with data at End of Season, inner join -> only players in both datasets
data2019=data2019.dropna() #Drop rows with blank values
data2019

     playerId  SO   PA     SO/PA
0         785  46  247  0.212425
1        1177  35  295  0.124771
2        1433  44  281  0.131679
3        1744  64  319  0.196721
4        2136  72  324  0.205674
..        ...  ..  ...       ...
267     19611  47  253  0.177043
268     19709  67  234  0.295699
269     19755  53  218  0.258824
270     19858  44  202  0.229064
271     20123  73  342  0.200303

[272 rows x 4 columns]

####Skipping 2020 as this was not a full traditional MLB season

### 2021 Data

Start: 4/1/21
ASG: 7/13/21
EOS: 10/3/21

In [13]:
#ASG data represents SO/PA at the midpoint of the baseball season (the All-Star Break)
ASG2021 = pd.read_csv(dir + '2021_Start_ASG_160_AB.csv') #Load in CSV (direct export from FanGraphs)
ASG2021 = ASG2021[['playerId','SO','PA']] #Remove unnecessary columns
ASG2021

     playerId  SO   PA
0        1177  29  208
1        1744  74  277
2        2136  53  329
3        2396  56  375
4        2434  57  318
..        ...  ..  ...
246     21523  70  316
247     21618  86  329
248     22168  67  239
249     26197  68  272
250     27506  47  201

[251 rows x 3 columns]

In [14]:
#EOS data represents SO/PA with full season data
EOS2021 = pd.read_csv(dir + '2021_Start_EOS_160_AB.csv') #Load in CSV (direct export from FanGraphs)
EOS2021 = EOS2021[['playerId','SO','PA']] #Remove unnecesaary columns
EOS2021['SO/PA'] = EOS2021['SO']/EOS2021['PA'] #Calculate strikeout rate
EOS2021=EOS2021.drop(columns=['PA','SO']) #Drop columns used for calculation
EOS2021

     playerId     SO/PA
0        1177  0.152027
1        1744  0.224335
2        2136  0.171004
3        2396  0.154780
4        2434  0.215753
..        ...       ...
379     24655  0.267327
380     26197  0.215352
381     27459  0.274809
382     27461  0.218579
383     27506  0.238255

[384 rows x 2 columns]

In [15]:
#Create merged data for 2021
data2021 = pd.merge(ASG2021, EOS2021, on=['playerId'], how='inner') #Merge data at All-Star_Break with data at End of Season, inner join -> only players in both datasets
data2021=data2021.dropna() #Drop rows with blank values
data2021

     playerId  SO   PA     SO/PA
0        1177  29  208  0.152027
1        1744  74  277  0.224335
2        2136  53  329  0.171004
3        2396  56  375  0.154780
4        2434  57  318  0.215753
..        ...  ..  ...       ...
246     21523  70  316  0.223455
247     21618  86  329  0.266187
248     22168  67  239  0.264642
249     26197  68  272  0.215352
250     27506  47  201  0.238255

[251 rows x 4 columns]

### 2022 Data

Start: 4/7/2022
ASG: 7/19/2022
EOS: 10/5/2022

In [16]:
#ASG data represents SO/PA at the midpoint of the baseball season (the All-Star Break)
ASG2022 = pd.read_csv(dir + '2022_Start_ASG_160_AB.csv') #Load in CSV (direct export from FanGraphs)
ASG2022 = ASG2022[['playerId','SO','PA']] #Remove unnecessary columns
ASG2022

     playerId  SO   PA
0        1744  74  309
1        2136  72  286
2        2396  41  281
3        2434  78  351
4        2967  86  346
..        ...  ..  ...
278     26288  34  182
279     26294  43  220
280     27465  76  298
281     27506  57  322
282     30116  57  211

[283 rows x 3 columns]

In [17]:
#EOS data represents SO/PA with full season data
EOS2022 = pd.read_csv(dir + '2022_Start_EOS_160_AB.csv') #Load in CSV (direct export from FanGraphs)
EOS2022 = EOS2022[['playerId','SO','PA']] #Remove unnecesaary columns
EOS2022['SO/PA'] = EOS2022['SO']/EOS2022['PA'] #Calculate strikeout rate
EOS2022=EOS2022.drop(columns=['PA','SO']) #Drop columns used for calculation
EOS2022

     playerId     SO/PA
0        1177  0.156695
1        1744  0.233256
2        2136  0.232653
3        2396  0.173913
4        2434  0.234714
..        ...       ...
382     27465  0.245050
383     27506  0.171821
384     27676  0.114094
385     27684  0.237113
386     30116  0.246637

[387 rows x 2 columns]

In [18]:
#Create merged data for 2022
data2022 = pd.merge(ASG2022, EOS2022, on=['playerId'], how='inner') #Merge data at All-Star_Break with data at End of Season, inner join -> only players in both datasets
data2022=data2022.dropna() #Drop rows with blank values
data2022

     playerId  SO   PA     SO/PA
0        1744  74  309  0.233256
1        2136  72  286  0.232653
2        2396  41  281  0.173913
3        2434  78  351  0.234714
4        2967  86  346  0.268489
..        ...  ..  ...       ...
278     26288  34  182  0.182979
279     26294  43  220  0.190987
280     27465  76  298  0.245050
281     27506  57  322  0.171821
282     30116  57  211  0.246637

[283 rows x 4 columns]

### Merging All Data

In [19]:
#Make dataframe with all years
Full_data=pd.concat([data2017, data2018, data2019, data2021, data2022]) #Concatenate all previous dataframes
Full_data.rename(columns = {'SO/PA':'EOS_SO/PA'}, inplace = True) #Rename to differentiate stats
Full_data

     playerId  SO   PA  EOS_SO/PA
0         393  37  286   0.144828
1         589  66  313   0.200393
2         785  67  322   0.217014
3         791  42  326   0.120861
4        1159  42  196   0.192529
..        ...  ..  ...        ...
278     26288  34  182   0.182979
279     26294  43  220   0.190987
280     27465  76  298   0.245050
281     27506  57  322   0.171821
282     30116  57  211   0.246637

[1355 rows x 4 columns]

### Define Inputs and Outputs, Test/Train Split

In [20]:
#Define X and Y variables
x=Full_data[['playerId','SO','PA']] #Only variables for ASG SO/PA
y=Full_data[['playerId','EOS_SO/PA']] #End of Season SO/PA

In [21]:
#Test/Train Split
X_train, X_test, Y_train, Y_test = train_test_split(x, y)

### Save/Export Full Dataset

In [22]:
#Export full dataframe
Full_data.to_csv('BaseballResearchFullDataNotCumulative_Spring26.csv')
#!cp BaseballResearchFullDataNotCumulative.csv "/content/drive/MyDrive/Research/Baseball/Data"
!cp BaseballResearchFullDataNotCumulative_Spring26.csv "/content/drive/MyDrive/Baseball/Data"

In [23]:
#Save Test/Train Split
np.savez('Baseball_Full_Train2.npz', xTrain=X_train, yTrain=Y_train)
np.savez('Baseball_Full_Test2.npz', xTest=X_test, yTest=Y_test)
!cp 'Baseball_Full_Train2.npz' "/content/drive/MyDrive/Baseball/Data"
!cp 'Baseball_Full_Test2.npz' "/content/drive/MyDrive/Baseball/Data"